### PR TITLE
0.12.1

### LINKED ISSUE #23: Getting recent versions of TFP merged
Issue: 
I am trying to build a package that uses tensorflow-probability and depends on conda-forge. I need a more recent version (>0.8) for this work and currently I'm stuck because the PRs opened for more recent versions of TFP have not been merged. I'm not sure if this is the right place for this request, but I was hoping that those PRs could have another look and get merged. 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by djsutherland**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #25, closes #24, closes #23, closes #22, closes #20, closes #19, closes #18, closes #17, closes #16, closes #14, and closes #12 if it works.

I don't know if bazel is actually needed for anything here, but might as well use the upstream build directions, if they work.

### CODE REVIEW

**Comment by djsutherland** [comment]
Theoretically, we should be able to pull tensorflow 2 in from `defaults`. In practice, I'm not getting that to work; I get cryptic incompatibility errors where I can't find the actual incompatibility. So this version – like the PyPI version, though for different reasons – just doesn't declare any dependency on tensorflow. It *should* work if the user has a working, compatible tensorflow installed.

Obviously, this isn't ideal, but it should be better than nothing until we get conda-forge builds of tf2 (https://github.com/conda-forge/tensorflow-feedstock/pull/110)....

**Comment by oblute** [comment]
@djsutherland I don't know if this approach really works within conda-forge - to me, it is a requirement that all dependencies exist within the conda-forge builds, and it seems like a recipe for setting up users with environment issues and import failures. I would be interested what the @conda-forge/core channel things about this change, as the new version of this is something that has been desired by many.

**Comment by beckermr** [comment]
I tend to agree that we should have consistent recipes. I realize TF is a pain point for a bunch of people. What is the timescale for our own builds and how is urgent is this PR compared to that?

**Comment by djsutherland** [comment]
I agree that of course we want consistent builds. But, well, TF2 came out 17 months ago, and getting it right in conda-forge is apparently really really hard (https://github.com/conda-forge/tensorflow-feedstock/pull/68 / https://github.com/conda-forge/tensorflow-feedstock/pull/101 / https://github.com/conda-forge/tensorflow-feedstock/pull/104 / https://github.com/conda-forge/tensorflow-feedstock/pull/110).

There have been several complaints about the outdatedness of TFP on conda-forge: see https://github.com/conda-forge/tensorflow-probability-feedstock/issues/3#issuecomment-775386853, and also the reason I'm here is I got an out-of-band request from a GPflow maintainer about our very out of date versions of that library confusing users.

I think, as far as I can tell, we have two options here:
1. Status quo; users say `conda install gpflow` (or `cleverhans`, `phasespace`, any other package depending on TFP), get an old version of TFP and therefore an old version of GPflow, and end up annoyed at either the package or at conda-forge.
2. This PR's version; when users say `conda install gpflow`, they either:
   1. Already have TF2 installed, everything is fine.
   2. Already have TF1 installed; things either immediately break on import, or confusingly crash when they're trying to do something, not sure.
   3. Don't have tensorflow installed; the first time they try to do any gpflow anything, it crashes with a clear `can't import tensorflow`-type error. They install tensorflow, and depending on their environment and setup, end up either in state (a), (b), or a state where conda tells them gpflow and tensorflow are conflicting. In (b) they end up annoyed at either us or gpflow, in (c) they end up annoyed at us.

I'm not sure about the relative probability of sub-parts of 2, which I guess determines which choice is overall better.

(It is maybe worth noting that `pip install tensorflow-probability` itself does _not_ install tensorflow, because of the dumb pip situation with `tensorflow` vs `tensorflow-gpu`.)

**Comment by beckermr** [comment]
I think the pip behavior settles this for me personally. We are mirroring that and so not doing any worse than anyone else. 

Given that, I'd be fine to merge. We should get more comments from @conda-forge/core before proceeding.

**Comment by isuruf** [comment]
You can turn off strict channel priority and make conda bring in `tensorflow` from defaults.

**Comment by beckermr** [comment]
I think @djsutherland tried this and found an error.

> Theoretically, we should be able to pull tensorflow 2 in from defaults. In practice, I'm not getting that to work; I get cryptic incompatibility errors where I can't find the actual incompatibility. So this version – like the PyPI version, though for different reasons – just doesn't declare any dependency on tensorflow. It should work if the user has a working, compatible tensorflow installed.

**Comment by isuruf** [comment]
@beckermr, see my comment above about strict channel priority

**Comment by beckermr** [comment]
Yup. @djsutherland tried this as far as I can tell. 

>  Theoretically, we should be able to pull tensorflow 2 in from defaults. In practice, I'm not getting that to work; I get cryptic incompatibility errors where I can't find the actual incompatibility.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
Trying again just in case the wires were crossed on this. Thanks @isuruf!

**Comment by beckermr** [comment]
ok @djsutherland it appears that the feedstock was not configured properly to build against defaults as @isuruf pointed out. I thought you had tried that but now I think not. Sorry for the trouble @isuruf and thank you very much for pointing out the fix!

**Comment by djsutherland** [comment]
Ah, yeah, I hadn't tried turning off strict channel priority; I thought it would pull in tf2 because a compatible version wasn't on conda-forge, but apparently not. Thanks!

**Comment by mayou36** [comment]
Gorgeous, many thanks for the merge!

**Pull request merged**
